import type { DrillItem } from '@shared/content';

import { cite } from '../sources';

/** Data & integration engineering, plus security, compliance and governance. */
export const DRILL_DATA_SEC: DrillItem[] = [
  // ── Data & Integration ───────────────────────────────────────────────────
  {
    id: 'd.ingest.sftp',
    mode: 'drill',
    nodeIds: ['data.ingest_patterns', 'data.quality'],
    difficulty: 'core',
    explanation:
      'The nightly file that does not arrive is the most common integration failure and the one least likely to be alarmed. An absence has no error to catch, so you need a deadline check that fires when nothing lands, otherwise the first person to notice is a business user looking at yesterday’s numbers.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer drops a nightly extract to a bucket at 03:40. What must your pipeline alert on that teams routinely forget?',
      choices: [
        { id: 'a', text: 'Parse failures on rows that break the declared schema', whyWrong: 'Important, and already handled everywhere: a malformed row throws, so the alarm exists.' },
        { id: 'b', text: 'The file failing to arrive by its agreed deadline' },
        { id: 'c', text: 'A header column renamed silently by the source system', whyWrong: 'Real, and schema drift surfaces as a visible mapping failure rather than as silence.' },
        { id: 'd', text: 'Downstream queries slowing as the table grows nightly', whyWrong: 'A performance trend, not a signal about whether tonight’s data landed at all.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'd.quality.quarantine',
    mode: 'drill',
    nodeIds: ['data.quality', 'data.messy'],
    difficulty: 'core',
    explanation:
      'Failing the whole batch on one bad row means a single supplier’s typo stops the business. Silently dropping it means nobody ever finds out. A quarantine table with the raw row and the reason keeps the pipeline moving and keeps the decision reversible.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: '2% of rows in a nightly load fail validation. What is the right behavior?',
      choices: [
        { id: 'a', text: 'Fail the whole batch and hold it for the supplier to fix', whyWrong: 'One supplier’s typo halts the business, and someone will disable the check to unblock a release.' },
        { id: 'b', text: 'Drop the failing rows and log a count in the run summary', whyWrong: 'Silent data loss. The 2% becomes 15% one week, in a counter nobody reads.' },
        { id: 'c', text: 'Load the good rows, quarantine the rest with the reason' },
        { id: 'd', text: 'Coerce the bad fields to defaults so the batch loads whole', whyWrong: 'Manufactures data that looks real and is not, which is worse than data that is missing.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 'd.schema.canonical',
    mode: 'drill',
    nodeIds: ['data.schema_map', 'data.quality'],
    difficulty: 'deep',
    explanation:
      'Mapping N systems pairwise is N-squared work and gets worse with every acquisition. A canonical model means each source needs one mapping in and one out, and disagreements surface as explicit reconciliation decisions rather than as silent inconsistencies.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Three acquired systems have three customer schemas, and a fourth acquisition is coming. What do you build?',
      choices: [
        { id: 'a', text: 'Pairwise mappings between each pair of source systems', whyWrong: 'Six mappings for three systems, ten for four, and every change touches several of them.' },
        { id: 'b', text: 'Adopt the largest system’s schema as the group standard', whyWrong: 'Tempting, and it bakes one business unit’s idiosyncrasies in as everyone’s truth.' },
        { id: 'c', text: 'Keep the schemas apart and reconcile them at query time', whyWrong: 'Pushes the reconciliation problem onto every consumer, forever, including the next acquisition.' },
        { id: 'd', text: 'A canonical customer model, one mapping per source' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 'd.cdc.deletes',
    mode: 'drill',
    nodeIds: ['data.cdc', 'sec.gdpr'],
    difficulty: 'edge',
    explanation:
      'Query-based CDC polls for rows changed since a watermark and therefore cannot see a row that no longer exists. Deleted records linger in the target indefinitely. Which is an ordinary bug until an erasure request arrives, at which point it is a compliance failure.',
    diagramId: 'cdc-cutover',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Why does query-based CDC on an updated_at column miss deletes?',
      choices: [
        { id: 'a', text: 'A deleted row is absent, so no query can observe it' },
        { id: 'b', text: 'A delete does not write the updated_at timestamp', whyWrong: 'Close, and the deeper point is that no row remains to carry a timestamp at all.' },
        { id: 'c', text: 'Deletes commit in a different transaction from updates', whyWrong: 'Not the mechanism. Transaction boundaries do not decide what a polling query can see.' },
        { id: 'd', text: 'The watermark advances past rows still being written', whyWrong: 'A real bug that loses updates during long transactions, not the reason deletes vanish.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'd.idempotency.key',
    mode: 'drill',
    nodeIds: ['data.idempotency'],
    difficulty: 'core',
    explanation:
      'An idempotency key must be derived from the business event, not from the delivery attempt. Message ids change on redelivery; a natural key built from the source system and its record identifier survives retries, replays and backfills alike.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'What makes a good idempotency key for ledger writes driven by a message queue?',
      choices: [
        { id: 'a', text: 'The message id the queue assigns on each redelivery', whyWrong: 'Redelivery and replay produce a fresh message id for the very same business event.' },
        { id: 'b', text: 'Source system plus source record id for the event' },
        { id: 'c', text: 'A content hash of the fully enriched payload', whyWrong: 'Any non-semantic field, an enrichment timestamp for one, changes the hash and the key.' },
        { id: 'd', text: 'The ingestion timestamp plus the consumer name', whyWrong: 'Different on every attempt by construction, so each retry writes the ledger again.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'd.connectors.limits',
    mode: 'drill',
    nodeIds: ['data.connectors', 'data.rate_limits'],
    difficulty: 'deep',
    explanation:
      'Enterprise SaaS quotas are usually per org, not per integration, so your backfill competes with the customer’s own business processes. Running it off-hours with a concurrency cap is basic courtesy and also the difference between a smooth integration and an angry email from their operations lead.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You need to backfill two years of records from the customer’s CRM. What do you agree before starting?',
      choices: [
        { id: 'a', text: 'That they raise the quota on your integration user', whyWrong: 'Usually not separable. Enterprise SaaS ceilings are set per org, not per integration.' },
        { id: 'b', text: 'Nothing up front: retry on 429 until the backfill lands', whyWrong: 'You would consume their quota all day and degrade the processes their staff depend on.' },
        { id: 'c', text: 'A run window and a concurrency cap on the shared quota' },
        { id: 'd', text: 'A raw database export rather than going via the API', whyWrong: 'Worth asking, and normally refused for a SaaS system the customer does not host.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 'd.stream.justify',
    mode: 'drill',
    nodeIds: ['data.batch_stream', 'del.discovery_scope'],
    difficulty: 'core',
    explanation:
      'Streaming has a real, permanent operational cost, so it needs a consumer that genuinely acts on fresher data. "Real-time" in a brief is usually an aspiration nobody has traced to a decision, and tracing it is often the single most valuable thing you do in discovery.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'The brief says "real-time". What is the question that settles whether you actually need streaming?',
      choices: [
        { id: 'a', text: '"What end-to-end latency do you need on this feed?"', whyWrong: 'Invites a number pulled from the air. Ask what consumes the data instead.' },
        { id: 'b', text: '"Do you run Kafka or Pub/Sub in production today?"', whyWrong: 'A solution-space question that skips whether streaming is warranted at all.' },
        { id: 'c', text: '"What is your peak event volume per second now?"', whyWrong: 'Sizing information. It shapes how you build it, never whether you should.' },
        { id: 'd', text: '"What decision changes if the data is 30 minutes old?"' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 'd.backpressure',
    mode: 'drill',
    nodeIds: ['data.rate_limits', 'data.batch_stream'],
    difficulty: 'edge',
    explanation:
      'An unbounded in-memory buffer converts a downstream slowdown into an out-of-memory crash, which loses everything buffered. A bounded queue that pushes back is less convenient and degrades predictably, which is what you want at 3am.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Your consumer buffers in memory when the downstream API slows down. What is wrong with that?',
      choices: [
        { id: 'a', text: 'An unbounded buffer turns a slowdown into an OOM crash' },
        { id: 'b', text: 'It adds queueing latency to every message in flight', whyWrong: 'True, and the least of the problems. Latency degrades; the crash loses data outright.' },
        { id: 'c', text: 'It burns CPU on collection as the heap keeps growing', whyWrong: 'A symptom on the way to the real failure, not the reason to change the design.' },
        { id: 'd', text: 'Buffered messages reorder relative to the source topic', whyWrong: 'A buffer preserves order. It is the crash, not the ordering, that loses the data.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'd.encoding',
    mode: 'drill',
    nodeIds: ['data.messy'],
    difficulty: 'core',
    explanation:
      'Mixed encodings in one feed are normal when several upstream systems export independently. Detecting per file and recording what was detected beats assuming UTF-8 and silently producing replacement characters that nobody notices until a customer name appears mangled on an invoice.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Some files in a feed are UTF-8 and some are Windows-1252. What do you do?',
      choices: [
        { id: 'a', text: 'Assume UTF-8 and substitute the invalid byte sequences', whyWrong: 'Silently corrupts names and addresses, discovered months later on a printed invoice.' },
        { id: 'b', text: 'Detect per file, and alert on low-confidence results' },
        { id: 'c', text: 'Have the customer standardize every exporter first', whyWrong: 'Correct in principle, and it will outlast your engagement by a comfortable margin.' },
        { id: 'd', text: 'Strip anything outside ASCII before parsing the rows', whyWrong: 'Destroys data, and mangles a large fraction of European customer names.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'd.replay.safety',
    mode: 'drill',
    nodeIds: ['data.idempotency', 'data.cdc'],
    difficulty: 'deep',
    explanation:
      'The question worth asking before you need it is whether the pipeline can be replayed from any point without double-counting. Designing for that up front turns an incident recovery from a research project into a documented procedure.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'multi',
      stem: 'What makes a pipeline safely replayable? Pick all that apply.',
      choices: [
        { id: 'a', text: 'Writes are idempotent on a stable business key' },
        { id: 'b', text: 'Source data is retained long enough to re-read the window' },
        { id: 'c', text: 'Derived aggregates are recomputed rather than incremented' },
        { id: 'd', text: 'The pipeline sends notifications as a side effect of processing', whyWrong: 'A replay would re-notify every customer. Side effects must be separated from computation to be replay-safe.' },
        { id: 'e', text: 'Each run assigns new surrogate keys', whyWrong: 'Guarantees duplicates on replay, since the same record gets a new identity each time.' },
      ],
      correctIds: ['a', 'b', 'c'],
    },
  },

  // ── Security & Compliance ────────────────────────────────────────────────
  {
    id: 's.hipaa.baa',
    mode: 'drill',
    nodeIds: ['sec.hipaa'],
    difficulty: 'core',
    explanation:
      'A BAA covers a specific list of services, not the whole provider. Using a service outside that list for PHI is a breach regardless of how the rest of the architecture looks, and checking the covered-services list is a ten-minute task that occasionally reshapes an entire design.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A healthcare customer has a BAA with the cloud provider. What must you still verify per service?',
      choices: [
        { id: 'a', text: 'That the region you deploy into sits inside the United States', whyWrong: 'Residency and HIPAA are separate concerns. A US region does not bring a service into scope.' },
        { id: 'b', text: 'That CMEK is enabled on every store holding the records', whyWrong: 'Good practice, and not what a BAA covers or turns on for any given service.' },
        { id: 'c', text: 'That the service appears on the covered-services list' },
        { id: 'd', text: 'That the agreement was renewed within the last year', whyWrong: 'Contract administration. It says nothing about whether this service is in scope.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 's.hipaa.minimum',
    mode: 'drill',
    nodeIds: ['sec.hipaa', 'sec.pii'],
    difficulty: 'deep',
    explanation:
      'Minimum necessary means an assistant should retrieve only the PHI required for the task at hand. Indexing an entire chart so the model "has context" is the design that fails review, and it is also the design that produces the permission-bleed incident.',
    citations: cite('genaiSecurity'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A clinical assistant answers questions about a patient’s current medication. What does minimum necessary imply?',
      choices: [
        { id: 'a', text: 'Retrieve records for that encounter, not the whole chart' },
        { id: 'b', text: 'Index the entire chart so the model has full context', whyWrong: 'Exactly the design that fails a HIPAA review, and it degrades retrieval quality besides.' },
        { id: 'c', text: 'De-identify the records before any of them are indexed', whyWrong: 'Would make patient-specific answers impossible. This is a clinical tool, not analytics.' },
        { id: 'd', text: 'Restrict access to clinicians and index the full record', whyWrong: 'Role restriction is a separate control. It does not satisfy minimum necessary on its own.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 's.eu_ai_act.tier',
    mode: 'drill',
    nodeIds: ['sec.eu_ai_act'],
    difficulty: 'deep',
    explanation:
      'The EU AI Act classifies by use, not by technology. The same model is low-risk summarizing documents and high-risk making or materially informing decisions about people. That distinction is exactly where scope creep becomes a compliance event, which is why an FDE has to hear it in the request.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Which change most likely moves a system into a higher EU AI Act risk tier?',
      choices: [
        { id: 'a', text: 'Switching the workload onto a larger frontier model', whyWrong: 'Classification follows the intended purpose, not the capability of the model behind it.' },
        { id: 'b', text: 'Going from summarizing CVs to ranking candidates' },
        { id: 'c', text: 'Adding years of extra training data to the tuning set', whyWrong: 'Changes accuracy, not the intended purpose the tier is actually assessed against.' },
        { id: 'd', text: 'Rolling the same use case out to far more employees', whyWrong: 'Scale alone does not move the tier. What the system is used for has to change.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 's.tenancy.models',
    mode: 'drill',
    nodeIds: ['sec.tenancy', 'del.tco'],
    difficulty: 'deep',
    explanation:
      'Tenancy is a trade between blast radius and unit economics. Shared infrastructure is cheapest and has the widest blast radius; a dedicated project per tenant is the opposite. Regulated customers frequently pay for isolation, and knowing which model you are selling is a scoping decision, not a deployment detail.',
    diagramId: 'tenancy-models',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'match',
      stem: 'Match each tenancy model to its defining trade-off.',
      pairs: [
        { left: 'Shared infrastructure, row-level isolation', right: 'Cheapest, widest blast radius' },
        { left: 'Dedicated project per tenant', right: 'Strong isolation, higher unit cost' },
        { left: 'Customer’s own cloud account', right: 'Their perimeter, hardest to operate' },
        { left: 'Shared compute, per-tenant encryption keys', right: 'Middle ground, key custody per tenant' },
      ],
    },
  },
  {
    id: 's.fedramp.timeline',
    mode: 'drill',
    nodeIds: ['sec.fedramp', 'cust.expectations'],
    difficulty: 'deep',
    explanation:
      'For public sector work the honest answer is usually about the authorization boundary and the timeline, not the technology. Saying so early loses you nothing and saves a procurement cycle; implying you can be authorized quickly is a promise that will be checked. Note also that inheriting an authorized platform is not the same as holding an authorization for your own service.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A federal agency asks whether your product can be deployed for them. What is the honest first answer?',
      choices: [
        { id: 'a', text: '"Yes, we run on FedRAMP-authorized infrastructure today"', whyWrong: 'The platform’s authorization is not yours. A common overclaim, and quickly exposed.' },
        { id: 'b', text: '"Yes, we can meet whatever level you hold us to"', whyWrong: 'A promise about a process with a multi-year timeline you do not control.' },
        { id: 'c', text: '"No, we do not currently serve the public sector"', whyWrong: 'Closes the door before you understand what they need, or by when.' },
        { id: 'd', text: 'Ask what authorization level they need, then be candid' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 's.gdpr.basis',
    mode: 'drill',
    nodeIds: ['sec.gdpr'],
    difficulty: 'deep',
    explanation:
      'Consent is one lawful basis among several, and it is often the weakest choice for an employment or contractual context because it can be withdrawn and is hard to argue is freely given. Asking which basis applies, rather than assuming consent, is what a DPO expects from a competent partner.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer wants to process employee data through an assistant. Their plan is to collect consent. What do you raise?',
      choices: [
        { id: 'a', text: 'That consent is weak here, so ask the DPO which basis fits' },
        { id: 'b', text: 'Nothing: consent is the safest basis they could pick', whyWrong: 'Often the weakest. It is withdrawable, and hard to argue is freely given by an employee.' },
        { id: 'c', text: 'That they must re-collect consent from staff each year', whyWrong: 'Invents a requirement, and reinforces the very basis that was the problem.' },
        { id: 'd', text: 'That GDPR does not reach data about their own staff', whyWrong: 'It plainly does. Employment data is personal data like any other.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 's.questionnaire.unknown',
    mode: 'drill',
    nodeIds: ['sec.soc2', 'cust.bad_news'],
    difficulty: 'core',
    explanation:
      'Security questionnaires are read by people who compare your answers against your architecture. One confident wrong answer costs more credibility than ten honest "not yet, here is the compensating control" answers, and the honest ones are usually accepted.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A 300-row security questionnaire contains twelve controls you do not have. What do you do?',
      choices: [
        { id: 'a', text: 'Answer yes where you expect the control by go-live', whyWrong: 'A false statement today, in a document their auditors will hold you to tomorrow.' },
        { id: 'b', text: 'Leave the twelve blank for the reviewer to come back on', whyWrong: 'Reads as evasion, and stalls the review while someone chases you for answers.' },
        { id: 'c', text: 'Answer no, and name the compensating control and date' },
        { id: 'd', text: 'Mark them not applicable so the review keeps moving', whyWrong: 'Invites the one follow-up question that exposes the answer as untrue.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 's.residency.metadata',
    mode: 'drill',
    nodeIds: ['sec.residency', 'ai.observability'],
    difficulty: 'edge',
    explanation:
      'Residency is usually scoped carefully for the primary data path and then leaked through the side channels: logs shipped to a central region, traces to a vendor, metrics to a SaaS dashboard. Those are the paths that fail an audit, because nobody drew them on the architecture diagram.',
    citations: cite('genaiSecurity'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'multi',
      stem: 'A customer requires EU-only. Which paths commonly leak data out and get missed? Pick all that apply.',
      choices: [
        { id: 'a', text: 'Application logs shipped to a central non-EU project' },
        { id: 'b', text: 'Traces sent to a third-party observability SaaS' },
        { id: 'c', text: 'Error reporting that includes request payloads' },
        { id: 'd', text: 'Encrypted backups within the same EU region', whyWrong: 'Same region, so no transfer occurs.' },
        { id: 'e', text: 'The primary database, once pinned to an EU region', whyWrong: 'This is the path everyone remembers to check. It is the side channels that fail audits.' },
      ],
      correctIds: ['a', 'b', 'c'],
    },
  },
  {
    id: 's.pii.deident',
    mode: 'drill',
    nodeIds: ['sec.pii'],
    difficulty: 'edge',
    explanation:
      'Removing direct identifiers is not the same as making a record non-identifying. Quasi-identifiers, postcode, date of birth, a rare diagnosis, combine to single people out, which is why re-identification risk has to be assessed rather than assumed away by deleting a name column.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer removed names and IDs from a dataset and calls it anonymised. What is your concern?',
      choices: [
        { id: 'a', text: 'The dataset has lost most of its analytical value now', whyWrong: 'True, and a separate concern from whether the records are genuinely anonymous.' },
        { id: 'b', text: 'Postcode and birth date still single individuals out' },
        { id: 'c', text: 'They should have encrypted the columns, not dropped them', whyWrong: 'Encryption protects at rest. It does not make a record non-identifying to a reader.' },
        { id: 'd', text: 'Nothing, dropping direct identifiers is what that means', whyWrong: 'The assumption behind nearly every published re-identification result.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 's.zero_trust.service',
    mode: 'drill',
    nodeIds: ['sec.zero_trust', 'gcp.iam'],
    difficulty: 'core',
    explanation:
      'A service account per workload with only the roles that workload needs is the whole of least privilege in practice. One shared account across services means a compromise anywhere reaches everything, and the audit log cannot tell you which service did what.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Six services share one service account "because it is simpler". What is the strongest argument to change it?',
      choices: [
        { id: 'a', text: 'It makes the IAM policy documents much longer to read', whyWrong: 'A cosmetic objection that will not persuade anyone working to a deadline.' },
        { id: 'b', text: 'Sharing one account is against documented best practice', whyWrong: 'An appeal to authority. Name the concrete consequence and you win the argument.' },
        { id: 'c', text: 'API quotas are counted per account, not per service', whyWrong: 'Sometimes true, and an operational footnote rather than the security case.' },
        { id: 'd', text: 'One compromise reaches all six, and nothing is traced' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 's.audit.evidence',
    mode: 'drill',
    nodeIds: ['sec.audit', 'del.handover'],
    difficulty: 'core',
    explanation:
      'Evidence a customer can generate themselves outlives your engagement. A dashboard or query they own answers the auditor next year; a report you exported answers it once, and then they have to call you.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'The customer will face an audit six months after you leave. What do you build for them?',
      choices: [
        { id: 'a', text: 'A saved query they own and can re-run themselves' },
        { id: 'b', text: 'A comprehensive evidence pack as a PDF at handover', whyWrong: 'A snapshot out of date within a week, and it cannot be regenerated without you.' },
        { id: 'c', text: 'A standing offer to help when the audit actually lands', whyWrong: 'Creates a dependency that whoever holds the account next may not honor.' },
        { id: 'd', text: 'Documentation of where each relevant log stream lives', whyWrong: 'Necessary, and it leaves the real work to someone already under audit pressure.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 's.soc2.scope',
    mode: 'drill',
    nodeIds: ['sec.soc2', 'sec.tenancy'],
    difficulty: 'edge',
    explanation:
      'A SOC 2 report covers a defined system boundary. A customer asking "are you SOC 2?" usually means "is the thing I am buying inside the boundary?", and a new deployment model or a new region frequently is not. Knowing your own scope is what makes that answer credible.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You hold SOC 2 Type II for your SaaS. A customer wants the product deployed into their own cloud account. What is true?',
      choices: [
        { id: 'a', text: 'The report covers your software wherever it happens to run', whyWrong: 'A report covers a system and the controls operating around it, never a binary.' },
        { id: 'b', text: 'It extends to the customer’s account once they deploy it', whyWrong: 'Their environment is their control responsibility, and outside your boundary.' },
        { id: 'c', text: 'That model likely sits outside the report’s system boundary' },
        { id: 'd', text: 'You cannot discuss it until a new report has been issued', whyWrong: 'You can discuss it honestly today. Naming the scope gap is the credible move.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 's.breach.first',
    mode: 'drill',
    nodeIds: ['sec.audit', 'cust.bad_news'],
    difficulty: 'edge',
    explanation:
      'Regulatory clocks start early and the customer must be told before they hear it elsewhere. Containment and notification run in parallel, waiting until you fully understand the incident is how a security event becomes a trust event and, in several regimes, a fine.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'order',
      stem: 'You discover your integration logged customer PHI to a non-compliant store. Order your first actions.',
      steps: [
        'Stop the logging path so no further data is written',
        'Notify your customer contact and their privacy officer, before they hear it elsewhere',
        'Scope what was written, when it started, and who could have accessed it',
        'Purge the data and document the remediation for their breach record',
      ],
    },
  },
];
