import type { DrillItem } from '@shared/content';

import { cite } from '../sources';

/** GCP Foundations: identity, networking, perimeters, compute, data, ops. */
export const DRILL_FOUNDATIONS: DrillItem[] = [
  {
    id: 'f.vpc.shared',
    mode: 'drill',
    nodeIds: ['gcp.vpc', 'gcp.hierarchy'],
    difficulty: 'core',
    explanation:
      'Shared VPC lets a central network team own subnets, routes and firewall rules in a host project while application teams deploy into service projects. It is the standard answer when a customer wants central network control without central deployment control. Which is almost every enterprise.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer’s network team insists on owning all subnets and firewall rules, but six product teams need to deploy their own services. What do you propose?',
      choices: [
        { id: 'a', text: 'Shared VPC: network team owns the host project, product teams deploy into service projects' },
        { id: 'b', text: 'One project per team, each with its own VPC, peered together', whyWrong: 'VPC peering is non-transitive, so six VPCs means fifteen peerings and a routing model nobody can reason about.' },
        { id: 'c', text: 'A single project everyone shares', whyWrong: 'No blast-radius separation and IAM becomes unmanageable. It also fails the first audit that asks about least privilege.' },
        { id: 'd', text: 'Each team runs their own VPN back to a central hub', whyWrong: 'Adds tunnels, bandwidth limits and an operational burden to solve a problem Shared VPC solves natively.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.vpc.peering',
    mode: 'drill',
    nodeIds: ['gcp.vpc'],
    difficulty: 'deep',
    explanation:
      'VPC peering is not transitive: if A peers with B and B peers with C, A cannot reach C. Teams discover this after building a hub-and-spoke topology that silently does not route, usually during an integration test the week before go-live.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Network A peers with hub B. Network C also peers with hub B. Can a VM in A reach a VM in C?',
      choices: [
        { id: 'a', text: 'No: VPC peering is not transitive' },
        { id: 'b', text: 'Yes, automatically through the hub', whyWrong: 'This is the assumption that breaks hub-and-spoke designs. Peering only connects the two networks directly involved.' },
        { id: 'c', text: 'Yes, if the hub has IP forwarding enabled', whyWrong: 'IP forwarding on an instance is unrelated; peering routes are simply not exported onward.' },
        { id: 'd', text: 'Only for internal load balancer traffic', whyWrong: 'No traffic class escapes the non-transitivity rule.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.psc.direction',
    mode: 'drill',
    nodeIds: ['gcp.psc', 'gcp.vpc'],
    difficulty: 'deep',
    explanation:
      'Private Service Connect works in both directions: consumer endpoints reach published services, and a service producer can publish into a consumer’s VPC. That second direction is what lets you deliver software into a customer’s network without asking them to open inbound firewall rules. A conversation that otherwise takes weeks.',
    diagramId: 'vpcsc-vs-psc',
    citations: cite('psc'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You need your managed service to be reachable from inside a customer’s VPC without them opening inbound internet access. What do you offer?',
      choices: [
        { id: 'a', text: 'Publish the service via Private Service Connect; they create a consumer endpoint in their VPC' },
        { id: 'b', text: 'Give them a public endpoint restricted by IP allowlist', whyWrong: 'Still egress to a public IP, which many regulated customers forbid outright. Allowlists also break when their NAT ranges change.' },
        { id: 'c', text: 'Ask them to peer their VPC with yours', whyWrong: 'Peering exposes the whole network on both sides and requires non-overlapping CIDR ranges you do not control.' },
        { id: 'd', text: 'Run a VPN tunnel per customer', whyWrong: 'Workable but heavy: tunnels to maintain, overlapping ranges to negotiate, and a support burden per customer.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.vpcsc.egress',
    mode: 'drill',
    nodeIds: ['gcp.vpcsc'],
    difficulty: 'edge',
    explanation:
      'A perimeter blocks legitimate traffic as readily as illegitimate traffic. Egress rules are how you punch a documented, auditable hole for a specific service account calling a specific service. Which is exactly the artefact a security team wants to see, rather than a perimeter someone disabled to unblock a deploy.',
    citations: cite('vpcsc'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'After enabling a VPC Service Controls perimeter, the customer’s nightly export to a partner project starts failing. What is the correct fix?',
      choices: [
        { id: 'a', text: 'Add an egress rule scoped to that service account and destination project' },
        { id: 'b', text: 'Move the perimeter to dry-run mode', whyWrong: 'Dry run stops enforcing entirely. It is a good diagnostic step and a terrible resting state.' },
        { id: 'c', text: 'Remove the partner project’s data from the perimeter', whyWrong: 'Solves the error by removing the protection the perimeter existed to provide.' },
        { id: 'd', text: 'Grant the service account project owner', whyWrong: 'IAM is not the constraint here. The perimeter blocks regardless of role, which is the entire point of it.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.iam.conditions',
    mode: 'drill',
    nodeIds: ['gcp.iam', 'sec.zero_trust'],
    difficulty: 'deep',
    explanation:
      'IAM conditions let you attach time, resource-name or request-attribute predicates to a binding. Time-bound elevated access is the standard answer to "we need break-glass admin". It satisfies the operational need without leaving a standing privileged principal for an auditor to find.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'An on-call engineer needs elevated access during incidents only. What keeps that from becoming standing privilege?',
      choices: [
        { id: 'a', text: 'An IAM condition that expires the binding, granted through a request-and-approve flow' },
        { id: 'b', text: 'A second account they only log into during incidents', whyWrong: 'Better than nothing, but the privilege is still permanent, it just lives on a different identity.' },
        { id: 'c', text: 'A quarterly access review', whyWrong: 'Detective and slow. Between reviews the privilege stands.' },
        { id: 'd', text: 'Documenting the expectation in the runbook', whyWrong: 'A policy nobody enforces. The binding is what an auditor reads.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.landing_zone.what',
    mode: 'drill',
    nodeIds: ['gcp.landing_zone', 'gcp.hierarchy'],
    difficulty: 'core',
    explanation:
      'A landing zone is the opinionated baseline, folder structure, network topology, org policies, logging sinks, identity federation, that every workload inherits. Arriving as an FDE, the first question is whether one exists: deploying into a customer with a mature landing zone is a different engagement from being the first workload in a bare organization.',
    diagramId: 'landing-zone',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'multi',
      stem: 'What does a landing zone typically define before any workload lands? Pick all that apply.',
      choices: [
        { id: 'a', text: 'Folder and project hierarchy with inherited org policies' },
        { id: 'b', text: 'Network topology, including shared VPC and connectivity to on-premises' },
        { id: 'c', text: 'Centralised logging and monitoring sinks' },
        { id: 'd', text: 'Identity federation from the corporate IdP' },
        { id: 'e', text: 'The application architecture for each workload', whyWrong: 'That is the workload’s business. A landing zone that dictates application design is an obstacle rather than a platform.' },
      ],
      correctIds: ['a', 'b', 'c', 'd'],
    },
  },
  {
    id: 'f.interconnect.choice',
    mode: 'drill',
    nodeIds: ['gcp.interconnect'],
    difficulty: 'core',
    explanation:
      'The deciding factors are bandwidth, latency predictability and lead time. Dedicated Interconnect gives the best performance and takes weeks to provision; Cloud VPN is available the same afternoon over the public internet. On a 90-day engagement, the lead time is usually the constraint that decides it.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'match',
      stem: 'Match each hybrid connectivity option to when you would choose it.',
      pairs: [
        { left: 'Need connectivity this week for a pilot', right: 'Cloud VPN' },
        { left: '10 Gbps sustained, predictable latency', right: 'Dedicated Interconnect' },
        { left: 'Want private connectivity without your own cross-connect', right: 'Partner Interconnect' },
        { left: 'Reaching Google APIs privately from on-prem', right: 'Private Service Connect' },
      ],
    },
  },
  {
    id: 'f.compute.gke_autopilot',
    mode: 'drill',
    nodeIds: ['gcp.gke', 'gcp.compute_choice'],
    difficulty: 'core',
    explanation:
      'Autopilot removes node management: Google runs the node pool, and you pay for requested pod resources. It is the right default when a customer wants Kubernetes semantics without a platform team, and the wrong choice when they need DaemonSets, privileged pods or specific node tuning.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer wants GKE but has no platform engineers. What pushes you toward Standard rather than Autopilot?',
      choices: [
        { id: 'a', text: 'They need privileged DaemonSets or specific node-level tuning' },
        { id: 'b', text: 'They want to minimize operational overhead', whyWrong: 'That is the argument for Autopilot, not against it.' },
        { id: 'c', text: 'Their workload is bursty', whyWrong: 'Autopilot handles bursty workloads well, you pay for what pods request.' },
        { id: 'd', text: 'They want per-pod billing', whyWrong: 'Also an argument for Autopilot.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.datastore.choice',
    mode: 'drill',
    nodeIds: ['gcp.spanner', 'gcp.alloydb', 'gcp.firestore', 'gcp.bigquery'],
    difficulty: 'core',
    explanation:
      'Pick by access pattern, not by prestige. Spanner earns its cost when you genuinely need horizontal write scale with strong consistency across regions; most enterprise workloads are a Postgres shape with a relational schema and joins, and reaching for Spanner there buys complexity nobody needed.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'match',
      stem: 'Match each workload to the datastore you would default to.',
      pairs: [
        { left: 'Relational schema, joins, single region, needs pgvector', right: 'AlloyDB' },
        { left: 'Globally distributed writes with strong consistency', right: 'Spanner' },
        { left: 'Analytical scans over billions of event rows', right: 'BigQuery' },
        { left: 'High-throughput time-series keyed by device', right: 'Bigtable' },
      ],
    },
  },
  {
    id: 'f.bq.slots',
    mode: 'drill',
    nodeIds: ['gcp.bigquery', 'gcp.billing', 'del.tco'],
    difficulty: 'deep',
    explanation:
      'On-demand bills per byte scanned and is ideal for spiky, unpredictable usage. Capacity (slot) pricing bills for reserved compute and wins once query volume is high and steady enough that the reservation stays busy. The crossover is a real calculation, and doing it in front of the customer is exactly the solutions-architect move.',
    citations: cite('bqPartition'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer’s BigQuery spend is high but extremely spiky, heavy month-end, near-idle otherwise. What do you recommend?',
      choices: [
        { id: 'a', text: 'Stay on-demand, and attack the bytes scanned with partitioning and column projection' },
        { id: 'b', text: 'Move to a large slot reservation', whyWrong: 'You would pay for reserved capacity that sits idle most of the month. Reservations reward steady load.' },
        { id: 'c', text: 'Export to Cloud Storage and query with an external table', whyWrong: 'External tables usually scan more, not less, and lose partition pruning.' },
        { id: 'd', text: 'Materialise every dashboard query nightly', whyWrong: 'Helps some queries, but it is a second system to maintain before you have done the free optimization.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.pubsub.deadletter',
    mode: 'drill',
    nodeIds: ['gcp.pubsub', 'data.quality'],
    difficulty: 'core',
    explanation:
      'Without a dead-letter topic, a permanently un-processable message is redelivered forever, consuming quota and hiding behind a subscription backlog that never drains. A dead-letter topic plus an alert on its depth turns a silent poison-pill into an actionable signal.',
    citations: cite('pubsubOrdering'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'One malformed message is stuck in a subscription and the backlog never drains. What is missing from the design?',
      choices: [
        { id: 'a', text: 'A dead-letter topic with a max delivery attempt count, plus an alert on its depth' },
        { id: 'b', text: 'A longer acknowledgment deadline', whyWrong: 'The message is not slow, it is un-processable. More time changes nothing.' },
        { id: 'c', text: 'More subscriber instances', whyWrong: 'Every instance will fail on the same message.' },
        { id: 'd', text: 'Ordering keys', whyWrong: 'Ordering makes it worse: a stuck message blocks its whole key.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.dataflow.windowing',
    mode: 'drill',
    nodeIds: ['gcp.dataflow', 'data.batch_stream'],
    difficulty: 'deep',
    explanation:
      'Event time is when it happened; processing time is when your pipeline saw it. Telematics from vehicles that lose signal in rural areas arrives late by definition, so windowing on processing time silently attributes an event to the wrong hour. Watermarks and allowed lateness are how you handle it honestly.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Telematics events sometimes arrive twenty minutes late because vehicles lose signal. Your hourly aggregates are wrong. What is the cause?',
      choices: [
        { id: 'a', text: 'Windowing on processing time rather than event time' },
        { id: 'b', text: 'Insufficient worker parallelism', whyWrong: 'A throughput concern. Late data would still land in the wrong window on a faster pipeline.' },
        { id: 'c', text: 'Missing deduplication', whyWrong: 'Duplicates inflate counts; they do not shift events between hours.' },
        { id: 'd', text: 'The sink is eventually consistent', whyWrong: 'Read consistency does not change which window an event was assigned to.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.dataplex.audit',
    mode: 'drill',
    nodeIds: ['gcp.dataplex', 'sec.audit'],
    difficulty: 'core',
    explanation:
      'When an auditor asks "where did this number come from?", the answer is lineage. Catalog and lineage tooling exists precisely so that question has a machine-generated answer rather than an analyst reconstructing it from memory three weeks later.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'An auditor asks which source systems feed a regulatory report and how each field was derived. What should already exist?',
      choices: [
        { id: 'a', text: 'Catalogued datasets with captured column-level lineage' },
        { id: 'b', text: 'A data dictionary maintained in a spreadsheet', whyWrong: 'Hand-maintained documentation drifts from reality the first time a pipeline changes.' },
        { id: 'c', text: 'Access logs for the report', whyWrong: 'Answers who read it, not where it came from.' },
        { id: 'd', text: 'The pipeline source code', whyWrong: 'Technically the ground truth, and not an answer an auditor can act on.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.observability.slo',
    mode: 'drill',
    nodeIds: ['gcp.observability', 'del.slo'],
    difficulty: 'deep',
    explanation:
      'An SLI must be measurable from the user’s perspective and tied to something you control. "Model quality" is neither. It is not continuously measurable in production without labels. Availability and latency of the serving path are, and they are what an SLO can meaningfully commit to.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'multi',
      stem: 'Which of these make workable SLIs for an AI assistant in production? Pick all that apply.',
      choices: [
        { id: 'a', text: 'Fraction of requests served without error' },
        { id: 'b', text: 'p95 time to first token' },
        { id: 'c', text: 'Fraction of answers that included at least one citation' },
        { id: 'd', text: 'Answer correctness on live traffic', whyWrong: 'Not continuously measurable without ground-truth labels on live traffic. Track it on an offline eval set instead, and do not put it in an SLO.' },
        { id: 'e', text: 'Customer satisfaction with the product overall', whyWrong: 'Lagging, confounded by everything else in the product, and not attributable to the serving path.' },
      ],
      correctIds: ['a', 'b', 'c'],
    },
  },
  {
    id: 'f.billing.quota',
    mode: 'drill',
    nodeIds: ['gcp.billing', 'del.pilot_to_prod'],
    difficulty: 'deep',
    explanation:
      'Quota is the failure mode that ambushes pilots. A configuration that works fine at demo volume hits a per-minute or per-region ceiling the day real traffic arrives, and quota increases take days to approve. Checking and requesting quota during scoping, not during load testing, is the difference between a smooth go-live and an embarrassing one.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You are scoping a pilot that will ramp to 400 requests per second in week eight. What do you do in week one?',
      choices: [
        { id: 'a', text: 'Check the relevant quotas for the target region and file increase requests immediately' },
        { id: 'b', text: 'Load test in week seven and raise quota if you hit a ceiling', whyWrong: 'Quota increases are reviewed by humans and can take days. Discovering the ceiling a week out is how launches slip.' },
        { id: 'c', text: 'Assume default quotas are generous enough', whyWrong: 'Defaults are sized for evaluation, not production, and vary by region and model.' },
        { id: 'd', text: 'Design to stay under the default by throttling users', whyWrong: 'Degrading the product to avoid an administrative request nobody made.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.scc.posture',
    mode: 'drill',
    nodeIds: ['gcp.scc', 'sec.audit'],
    difficulty: 'core',
    explanation:
      'Security Command Center surfaces misconfiguration and threat findings across the org. For an FDE the practical value is arriving at a customer and being able to see, rather than ask, what the posture actually is, and being able to hand the security team a dashboard rather than a promise.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'The customer’s CISO asks how they will know whether your deployment weakened their posture. What do you point at?',
      choices: [
        { id: 'a', text: 'Security Command Center findings scoped to the new projects, reviewed before and after' },
        { id: 'b', text: 'Your team’s internal security checklist', whyWrong: 'Your assurance about your own work. The CISO needs evidence from their own tooling.' },
        { id: 'c', text: 'The provider’s compliance certifications', whyWrong: 'Covers the platform, not what you configured on top of it.' },
        { id: 'd', text: 'A penetration test after go-live', whyWrong: 'Valuable and late. It does not answer the question during the engagement.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.kms.rotation',
    mode: 'drill',
    nodeIds: ['gcp.kms'],
    difficulty: 'deep',
    explanation:
      'Rotating a key creates a new primary version for new encryptions; existing data stays readable under its original version. This surprises people who expect rotation to re-encrypt everything. It does not, and that is what makes rotation cheap enough to do on a schedule.',
    citations: cite('cmek'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer asks what happens to existing data when their CMEK key rotates. What is correct?',
      choices: [
        { id: 'a', text: 'Existing data stays encrypted under its previous key version and remains readable; new writes use the new primary' },
        { id: 'b', text: 'All data is re-encrypted automatically with the new version', whyWrong: 'Rotation does not rewrite existing ciphertext. That would be prohibitively expensive at scale.' },
        { id: 'c', text: 'Existing data becomes unreadable until manually re-encrypted', whyWrong: 'Old versions remain enabled for decryption. This would make rotation unusable.' },
        { id: 'd', text: 'Nothing changes until you disable the old version', whyWrong: 'New writes immediately use the new primary version.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.orgpolicy.regions',
    mode: 'drill',
    nodeIds: ['gcp.hierarchy', 'sec.residency'],
    difficulty: 'core',
    explanation:
      'A resource-location constraint applied at the folder is evaluated when a resource is created, so a non-compliant deployment fails rather than succeeding and being caught later. This is the difference between a residency commitment you can demonstrate and one you can only promise.',
    diagramId: 'landing-zone',
    citations: cite('assured'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'How do you make an EU-only residency commitment technically enforced rather than merely documented?',
      choices: [
        { id: 'a', text: 'A resource-location org policy constraint on the folder, so non-EU creation fails' },
        { id: 'b', text: 'A Terraform module that only allows EU regions', whyWrong: 'Good hygiene, trivially bypassed by anyone using the console or a different module.' },
        { id: 'c', text: 'A monthly report of resource locations', whyWrong: 'Detective. The breach already happened by the time it appears.' },
        { id: 'd', text: 'A clause in the statement of work', whyWrong: 'Contractual, not technical. It is what you fall back on after the incident.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.iam.groups',
    mode: 'drill',
    nodeIds: ['gcp.iam', 'del.handover'],
    difficulty: 'intro',
    explanation:
      'Binding roles to groups rather than individuals means access changes happen in the customer’s existing identity system, where their joiner-mover-leaver process already lives. Binding to individuals means every staffing change becomes a ticket for you, and one of them will be missed.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You are setting up access for the customer’s team, knowing you hand over in twelve weeks. What do you bind roles to?',
      choices: [
        { id: 'a', text: 'Groups synced from their corporate directory' },
        { id: 'b', text: 'Individual user accounts', whyWrong: 'Every joiner and leaver becomes a change you have to make, and after handover, one nobody makes.' },
        { id: 'c', text: 'A shared service account the team uses', whyWrong: 'Destroys attribution in the audit log and cannot be revoked per person.' },
        { id: 'd', text: 'Domain-wide bindings', whyWrong: 'Grants far more people access than intended.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.firestore.model',
    mode: 'drill',
    nodeIds: ['gcp.firestore'],
    difficulty: 'core',
    explanation:
      'Document stores reward designing around the read you will perform most often, because there are no joins to rescue a poor layout. The classic mistake is normalising as though it were relational and then discovering the main screen needs four round trips.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You are modeling data in Firestore for a screen that shows an order with its line items. What is the usual right instinct?',
      choices: [
        { id: 'a', text: 'Shape the document around that read, denormalising line items into or under the order' },
        { id: 'b', text: 'Normalize into separate collections and join in the client', whyWrong: 'There are no server-side joins; you would be issuing N reads per screen.' },
        { id: 'c', text: 'Store everything in one collection with a type field', whyWrong: 'Makes queries and security rules harder without buying anything.' },
        { id: 'd', text: 'Mirror the relational schema exactly', whyWrong: 'Carries relational assumptions into a store that cannot honour them.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.wif.trust',
    mode: 'drill',
    nodeIds: ['gcp.wif', 'sec.zero_trust'],
    difficulty: 'edge',
    explanation:
      'A workload identity pool provider must constrain which external identities may exchange a token, by repository, branch, subject or audience. Omitting the attribute condition means anyone with a token from that issuer can impersonate your service account, which converts a keyless setup into a worse-than-keys setup.',
    citations: cite('wif'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You configure Workload Identity Federation for GitHub Actions. What must you not omit?',
      choices: [
        { id: 'a', text: 'An attribute condition restricting which repository and branch may exchange a token' },
        { id: 'b', text: 'A key rotation schedule', whyWrong: 'There are no keys: that is the point of federation.' },
        { id: 'c', text: 'A service account key as a fallback', whyWrong: 'Reintroduces exactly the credential you removed.' },
        { id: 'd', text: 'A firewall rule for GitHub’s IP ranges', whyWrong: 'The token exchange is not IP-bound, and those ranges change.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.cloudrun.concurrency',
    mode: 'drill',
    nodeIds: ['gcp.compute_choice', 'ai.latency', 'del.tco'],
    difficulty: 'deep',
    explanation:
      'Cloud Run bills for instance time, and a container that spends most of a request waiting on a model API is idle, not busy. Raising concurrency lets one instance serve many in-flight requests, which for LLM proxying is often a several-fold cost reduction with no latency penalty.',
    citations: cite('cloudRun'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Your Cloud Run service mostly waits on a model API. Costs are higher than expected. What is the first lever?',
      choices: [
        { id: 'a', text: 'Raise per-instance concurrency so one instance handles many in-flight requests' },
        { id: 'b', text: 'Increase CPU allocation per instance', whyWrong: 'The container is I/O-bound, not CPU-bound. More CPU costs more and changes nothing.' },
        { id: 'c', text: 'Set minimum instances higher', whyWrong: 'Reduces cold starts and increases cost. Wrong direction for a cost problem.' },
        { id: 'd', text: 'Move to GKE', whyWrong: 'A platform migration to avoid changing one setting.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.logging.sinks',
    mode: 'drill',
    nodeIds: ['gcp.observability', 'sec.audit'],
    difficulty: 'core',
    explanation:
      'Compliance regimes require audit logs to be retained beyond the default window and to be tamper-evident. A log sink to a bucket with retention lock or to a dedicated log bucket is the standard answer; relying on the default retention is how a customer discovers in month seven that the evidence they need has aged out.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Their compliance team needs seven years of admin activity logs, tamper-evident. What do you set up?',
      choices: [
        { id: 'a', text: 'A log sink to a dedicated bucket with a retention policy locked against deletion' },
        { id: 'b', text: 'Extend the default log retention setting', whyWrong: 'Default retention is capped well below seven years and is not tamper-evident.' },
        { id: 'c', text: 'Export logs nightly with a scheduled job', whyWrong: 'A job that can silently fail, and produces copies nobody can prove are complete.' },
        { id: 'd', text: 'Enable Access Transparency', whyWrong: 'Different concern: it shows provider access, not the customer’s own admin activity.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.hierarchy.blast',
    mode: 'drill',
    nodeIds: ['gcp.hierarchy', 'sec.tenancy'],
    difficulty: 'core',
    explanation:
      'The project is the unit of blast radius, quota and billing. Putting production and non-production in one project means a runaway job in dev consumes production quota and a compromised dev credential touches production data. A finding that shows up in every security review that bothers to look.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer proposes putting dev, staging and production in one project "to keep it simple". What is your strongest objection?',
      choices: [
        { id: 'a', text: 'The project is the unit of quota, billing and blast radius. A dev incident would take production with it' },
        { id: 'b', text: 'It makes Terraform harder to write', whyWrong: 'A tooling inconvenience, not a risk argument, and it will not persuade anyone.' },
        { id: 'c', text: 'You cannot use different regions per environment', whyWrong: 'Not true: regions are per resource.' },
        { id: 'd', text: 'Billing reports will be less detailed', whyWrong: 'Real but minor, and labels partly address it. It is not the reason to separate.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.alloydb.vector',
    mode: 'drill',
    nodeIds: ['gcp.alloydb', 'gcp.vector_search', 'ai.hybrid_search'],
    difficulty: 'deep',
    explanation:
      'Keeping vectors in the same database as the relational data lets a single SQL statement filter by tenant, ACL and date while ranking by vector distance. That pre-filtering is what makes top-k meaningful for a multi-tenant application, and it is the argument that usually settles the "do we need a vector database?" debate.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'multi',
      stem: 'What does keeping embeddings in AlloyDB alongside your relational data buy you? Pick all that apply.',
      choices: [
        { id: 'a', text: 'Pre-filtering by tenant and ACL in the same query that ranks by distance' },
        { id: 'b', text: 'Transactional consistency between a document and its embedding' },
        { id: 'c', text: 'One system to back up, monitor and secure instead of two' },
        { id: 'd', text: 'Better recall than any dedicated vector index at any scale', whyWrong: 'Overclaim. Dedicated indexes win at large scale and high query volume; the trade is real.' },
        { id: 'e', text: 'Automatic re-embedding when a document changes', whyWrong: 'Nothing does this for you. Keeping embeddings fresh is your pipeline’s job.' },
      ],
      correctIds: ['a', 'b', 'c'],
    },
  },
  {
    id: 'f.assured.tradeoff',
    mode: 'drill',
    nodeIds: ['gcp.assured', 'del.pilot_to_prod'],
    difficulty: 'edge',
    explanation:
      'Compliance-constrained environments deliberately restrict which services and regions are available, and new capabilities reach them later. Telling a customer up front that their Assured Workloads folder will lag on the newest model configuration is far better than discovering it during their security review.',
    citations: cite('assured'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'What should you warn a customer about before they place the AI workload inside an Assured Workloads folder?',
      choices: [
        { id: 'a', text: 'The available service and region set is restricted, and new capabilities arrive there later' },
        { id: 'b', text: 'It significantly increases latency', whyWrong: 'Not inherently: latency follows region choice, which is constrained but not slow.' },
        { id: 'c', text: 'It prevents using CMEK', whyWrong: 'The opposite: key management constraints are part of what it enforces.' },
        { id: 'd', text: 'It requires a separate billing account', whyWrong: 'Not a requirement.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.psc.dns',
    mode: 'drill',
    nodeIds: ['gcp.psc', 'gcp.vpc'],
    difficulty: 'edge',
    explanation:
      'A private endpoint is only useful if the client resolves the service name to it. Without a private DNS zone overriding the public record, clients resolve the public address and traffic leaves the private path. The failure is silent and looks like everything is fine until someone reads a flow log.',
    citations: cite('psc'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You created a Private Service Connect endpoint but traffic still leaves via the public path. What did you most likely miss?',
      choices: [
        { id: 'a', text: 'A private DNS zone resolving the service hostname to the endpoint address' },
        { id: 'b', text: 'A firewall rule allowing egress', whyWrong: 'Traffic is flowing, just over the wrong path. A blocked rule would fail, not reroute.' },
        { id: 'c', text: 'IAM permissions on the endpoint', whyWrong: 'Would produce authorisation errors, not a silent public path.' },
        { id: 'd', text: 'A VPC Service Controls perimeter', whyWrong: 'A different control. It would block exfiltration, not redirect resolution.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.gke.workload_identity',
    mode: 'drill',
    nodeIds: ['gcp.gke', 'gcp.iam', 'sec.zero_trust'],
    difficulty: 'deep',
    explanation:
      'GKE Workload Identity binds a Kubernetes service account to a Google service account, so pods obtain short-lived credentials without a mounted key file. Mounting a key as a secret is the pattern it replaces, and it is the one auditors find first.',
    citations: cite('wif'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'How should a pod in GKE authenticate to BigQuery?',
      choices: [
        { id: 'a', text: 'Workload Identity binding its Kubernetes service account to a Google service account' },
        { id: 'b', text: 'A service account key mounted as a Kubernetes secret', whyWrong: 'A long-lived credential sitting in etcd and in every pod that mounts it.' },
        { id: 'c', text: 'The node’s default service account', whyWrong: 'Every pod on the node shares it, so least privilege is impossible.' },
        { id: 'd', text: 'An API key in an environment variable', whyWrong: 'BigQuery does not authenticate this way, and env vars leak through logs and crash dumps.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.bigtable.rowkey',
    mode: 'drill',
    nodeIds: ['gcp.firestore', 'data.batch_stream'],
    difficulty: 'edge',
    explanation:
      'Bigtable distributes by row key prefix, so a monotonically increasing key such as a timestamp sends all writes to one tablet. Prefixing with a well-distributed field, device id, hashed tenant, spreads the load. This is the single most common Bigtable design error.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A Bigtable table keyed by timestamp is hotspotting badly under write load. What is the fix?',
      choices: [
        { id: 'a', text: 'Prefix the row key with a well-distributed field such as device id' },
        { id: 'b', text: 'Add more nodes to the cluster', whyWrong: 'Every write still targets one tablet on one node. Capacity does not fix key distribution.' },
        { id: 'c', text: 'Batch writes into larger mutations', whyWrong: 'Same tablet, fewer round trips. The hotspot persists.' },
        { id: 'd', text: 'Switch to a column-oriented schema', whyWrong: 'Bigtable is already wide-column; this does not address the key.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'f.terraform.state',
    mode: 'drill',
    nodeIds: ['gcp.landing_zone', 'del.handover'],
    difficulty: 'core',
    explanation:
      'Infrastructure the customer cannot reproduce is infrastructure you can never leave. Checked-in configuration with remote state in their own project means handover is a repository transfer rather than an ongoing dependency on the person who clicked through the console.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You are three weeks in and moving fast. What is the strongest argument against configuring things in the console for now?',
      choices: [
        { id: 'a', text: 'Anything not in code is something the customer cannot reproduce or take over at handover' },
        { id: 'b', text: 'The console is slower to use', whyWrong: 'It is usually faster in the moment, which is exactly why the trap works.' },
        { id: 'c', text: 'Console changes are not logged', whyWrong: 'They are logged in admin activity. Auditability is not the gap.' },
        { id: 'd', text: 'You cannot use the console in a compliance environment', whyWrong: 'You generally can; access is constrained rather than removed.' },
      ],
      correctId: 'a',
    },
  },
];
