import type { DrillItem } from '@shared/content';

import { cite } from '../sources';

/** Delivery economics and customer craft. The half of the job that is not code. */
export const DRILL_DELIVERY: DrillItem[] = [
  // ── Delivery & Economics ─────────────────────────────────────────────────
  {
    id: 'v.scope.boundary',
    mode: 'drill',
    nodeIds: ['del.discovery_scope', 'cust.saying_no'],
    difficulty: 'core',
    explanation:
      'A scope document is only useful if it says what is out. Listing only inclusions leaves every omission arguable, and the argument happens in week nine when there is no room to absorb it. The other three answers are all real artifacts worth having, and each of them assumes the boundary already exists: a deliverables list enumerates what is in, a change control board processes movement across a line, and a signed contract gives you recourse rather than agreement.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'What makes a scope statement actually hold when pressure arrives?',
      choices: [
        { id: 'a', text: 'A deliverables list detailed down to individual screens and reports', whyWrong: 'Inclusions alone leave every omission arguable, and it gets argued in week nine.' },
        { id: 'b', text: 'A change control board that meets weekly to review requests', whyWrong: 'The machinery for handling change, which needs an agreed baseline to change from.' },
        { id: 'c', text: 'An explicit out-of-scope list agreed alongside the in-scope list' },
        { id: 'd', text: 'A fixed-price statement of work signed by both legal teams', whyWrong: 'Legal recourse is not the same as matched expectations about what was excluded.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 'v.risk.first',
    mode: 'drill',
    nodeIds: ['del.risk_sequencing', 'del.thin_slice'],
    difficulty: 'core',
    explanation:
      'Sequence by what could kill the project, not by what is comfortable. The purpose of the first two weeks is to find out whether the thing is possible, building the easy layers first feels productive and defers the only question that matters. Data access ranks first for two reasons: nothing else can be validated without it, and it runs through people you do not control, so the lead time is not yours to compress.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Four workstreams: UI, data access negotiation, model quality on their corpus, and deployment automation. Which goes first?',
      choices: [
        { id: 'a', text: 'Deployment automation, so the pipeline is ready when the model is', whyWrong: 'Automating delivery for a system that may still turn out to be infeasible.' },
        { id: 'b', text: 'Model quality on their corpus, since it is the hardest to move', whyWrong: 'The right instinct in the wrong order: you cannot measure quality without the corpus.' },
        { id: 'c', text: 'The UI, so stakeholders can see and react to progress early', whyWrong: 'Visible progress that retires no risk, and it raises expectations while doing it.' },
        { id: 'd', text: 'Data access negotiation, since it gates every other check' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 'v.pilot.gap',
    mode: 'drill',
    nodeIds: ['del.pilot_to_prod'],
    difficulty: 'deep',
    explanation:
      'The pilot-to-production gap is mostly non-functional: security review, SLOs, on-call, data volume, error handling, access management. Teams estimate it as "a couple of weeks of hardening" and it routinely takes longer than the pilot did.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'multi',
      stem: 'What typically sits between a working pilot and production? Pick all that apply.',
      choices: [
        { id: 'a', text: 'A full security review and remediation of its findings' },
        { id: 'b', text: 'Agreed SLOs and someone on call to defend them' },
        { id: 'c', text: 'Behavior at real data volume rather than pilot volume' },
        { id: 'd', text: 'Access management for the real user population' },
        { id: 'e', text: 'Better model accuracy', whyWrong: 'Sometimes needed, and it is rarely what blocks a working pilot from shipping. The blockers are almost always non-functional.' },
      ],
      correctIds: ['a', 'b', 'c', 'd'],
    },
  },
  {
    id: 'v.napkin.tokens',
    mode: 'drill',
    nodeIds: ['del.napkin', 'ai.cost'],
    difficulty: 'core',
    explanation:
      'Doing this arithmetic out loud in the room is a solutions-architect superpower. 5,000 agents × 30 conversations × 22 working days ≈ 3.3M conversations per month; at roughly 10k tokens each that is about 33 billion tokens. The point is not precision. It is knowing within a few minutes whether the idea is affordable.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: '5,000 agents, 30 conversations each per working day, ~10k tokens per conversation. Roughly how many tokens per month?',
      choices: [
        { id: 'a', text: 'About 1.5 billion', whyWrong: 'The daily total. Multiplying by the 22 working days is the step that got skipped.' },
        { id: 'b', text: 'About 33 billion' },
        { id: 'c', text: 'About 330 billion', whyWrong: 'Ten times high, as if each conversation ran to 100k tokens rather than 10k.' },
        { id: 'd', text: 'About 150 million', whyWrong: 'Two orders of magnitude low, and that is an error that reaches a price quote.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'v.napkin.index',
    mode: 'drill',
    nodeIds: ['del.napkin', 'gcp.vector_search'],
    difficulty: 'deep',
    explanation:
      'A float32 vector of 768 dimensions is about 3 KB. Four million of them is roughly 12 GB before index overhead, which typically adds a substantial multiple. Knowing this stops you promising an in-memory index that will not fit on the instance the customer already budgeted for.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: '4 million chunks, 768-dimension float32 embeddings. Roughly how much memory for the raw vectors?',
      choices: [
        { id: 'a', text: 'Around 12 GB' },
        { id: 'b', text: 'Around 1.2 GB', whyWrong: 'Ten times low: this counts one byte per dimension rather than four.' },
        { id: 'c', text: 'Around 120 GB', whyWrong: 'Ten times high. 4 million times 3 KB is 12 GB, not 120.' },
        { id: 'd', text: 'Around 3 GB', whyWrong: 'That is a million vectors at 3 KB each. The count here is four million.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'v.poc.criteria',
    mode: 'drill',
    nodeIds: ['del.poc_exit', 'cust.expectations'],
    difficulty: 'core',
    explanation:
      'The prior vendor at Northwind failed because success was judged on the worst 5% of deliveries, which nobody had agreed in advance. Naming the tail behavior in the exit criterion, not just the average, is what prevents the same outcome.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A previous vendor "was accurate on average" and still failed the pilot. What belongs in your exit criterion that theirs lacked?',
      choices: [
        { id: 'a', text: 'A higher average accuracy target, 95% rather than 90%', whyWrong: 'Raises a bar that was never the one being judged in the first place.' },
        { id: 'b', text: 'A stated bound on worst-case behavior, not only an average' },
        { id: 'c', text: 'A longer pilot period with more volume flowing through', whyWrong: 'More time to fail the same test that nobody had written down.' },
        { id: 'd', text: 'A wider review panel drawn from every affected team', whyWrong: 'More opinions about a standard that is still undefined.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'v.slo.shared',
    mode: 'drill',
    nodeIds: ['del.slo', 'del.tco'],
    difficulty: 'deep',
    explanation:
      'You cannot offer an availability number above what your dependencies deliver. Committing to 99.99% while sitting on a 99.9% dependency means signing up for penalties you will pay. The arithmetic is unforgiving and worth doing before the contract. The useful move is not to refuse the target: it is to name the redundancy that would actually reach it, a second provider with automatic failover and the evaluation work to keep both answers acceptable, and then price that so the customer can decide whether the ninth is worth what it costs.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer wants 99.99% for a service whose model dependency publishes 99.9%. What do you say?',
      choices: [
        { id: 'a', text: 'Agree to 99.99% and cover the gap with retries and backoff', whyWrong: 'Retries mask transient errors. They do not lift you above a dependency’s ceiling.' },
        { id: 'b', text: 'Agree, and rely on the dependency beating its published number', whyWrong: 'Betting contractual penalties on someone else exceeding their own SLA.' },
        { id: 'c', text: 'Offer 99.9% and decline to discuss anything above it', whyWrong: 'Matching the dependency is right; refusing to price redundancy is not.' },
        { id: 'd', text: 'Explain that beating 99.9% needs redundancy across providers' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 'v.handover.runbook',
    mode: 'drill',
    nodeIds: ['del.handover'],
    difficulty: 'core',
    explanation:
      'A handover succeeds when the receiving team has already handled a real incident with you watching rather than doing. Documentation they have never used is documentation they will not trust at 3am.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Two weeks before handover, what best predicts that it will actually stick?',
      choices: [
        { id: 'a', text: 'Their team resolved a live incident with you watching only' },
        { id: 'b', text: 'A complete runbook covering every known failure mode and its fix', whyWrong: 'Necessary, and untested documentation is a hypothesis rather than a capability.' },
        { id: 'c', text: 'A recorded architecture walkthrough with a live question session', whyWrong: 'Passive transfer. Nobody replays a recording in the middle of an incident.' },
        { id: 'd', text: 'Six months of paid support starting at the handover date', whyWrong: 'Postpones the handover rather than completing it, and the dependency persists.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'v.tco.compare',
    mode: 'drill',
    nodeIds: ['del.tco'],
    difficulty: 'deep',
    explanation:
      'A TCO comparison that omits the people cost is not a comparison. Self-hosting trades a platform bill for engineer time, and engineer time is usually the larger and more permanent number, but only if you put it in the table.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'multi',
      stem: 'What belongs in a TCO comparison between a managed service and self-hosting? Pick all that apply.',
      choices: [
        { id: 'a', text: 'Engineer time to build and to operate, at a loaded rate' },
        { id: 'b', text: 'The cost of on-call coverage' },
        { id: 'c', text: 'Idle capacity during low-utilisation periods' },
        { id: 'd', text: 'Migration cost if the decision is reversed' },
        { id: 'e', text: 'Only the monthly infrastructure and license bill', whyWrong: 'The comparison that makes self-hosting look cheap. It is the one every vendor evaluation starts with and none should end with.' },
      ],
      correctIds: ['a', 'b', 'c', 'd'],
    },
  },
  {
    id: 'v.thin_slice.week2',
    mode: 'drill',
    nodeIds: ['del.thin_slice', 'del.risk_sequencing'],
    difficulty: 'deep',
    explanation:
      'The test of a thin slice is whether it could fail. A slice that cannot possibly fail has proven nothing. The entire value is in touching every layer with one real record so the risky part gets exercised early enough to act on.',
    diagramId: 'thin-slice',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'How do you tell whether a proposed thin slice is worth building?',
      choices: [
        { id: 'a', text: 'Check that it can be built and shown inside two weeks', whyWrong: 'A schedule test, not a value test. Plenty of two-week builds prove nothing.' },
        { id: 'b', text: 'Check that stakeholders will find the result impressive', whyWrong: 'Optimizes the slice for the demo rather than for information.' },
        { id: 'c', text: 'Ask what could go wrong when you run it end to end' },
        { id: 'd', text: 'Check that it reuses components the team already has', whyWrong: 'An efficiency argument, unrelated to how much uncertainty the slice retires.' },
      ],
      correctId: 'c',
    },
  },

  // ── Customer Craft ───────────────────────────────────────────────────────
  {
    id: 'c.exec.answer_first',
    mode: 'drill',
    nodeIds: ['cust.exec_comms'],
    difficulty: 'core',
    explanation:
      'Executives read top-down and stop when they have what they need. Answer first, then the two or three reasons, then detail on request. Building to a conclusion is how engineers write and how executives stop listening.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'order',
      stem: 'Order a status update for a steering committee.',
      steps: [
        'The answer: on track for the 14th, with one risk',
        'The risk and what you are doing about it',
        'What you need from them, if anything',
        'Supporting detail, available if asked',
      ],
    },
  },
  {
    id: 'c.exec.slide',
    mode: 'drill',
    nodeIds: ['cust.exec_comms', 'cust.expectations'],
    difficulty: 'core',
    explanation:
      'An architecture diagram in front of an executive audience answers a question they did not ask and invites scrutiny of decisions they cannot evaluate. Lead with the business outcome; keep the architecture in the appendix for the person who asks.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You have one slide for a CFO. What goes on it?',
      choices: [
        { id: 'a', text: 'The architecture diagram, annotated with the data flows', whyWrong: 'Answers a question they did not ask, and invites scrutiny they cannot apply.' },
        { id: 'b', text: 'The business outcome, how it is measured, and run cost' },
        { id: 'c', text: 'The delivery timeline with milestones and dependencies', whyWrong: 'A steering-committee artifact. A CFO is deciding whether to fund it, not to track it.' },
        { id: 'd', text: 'A model accuracy chart against the current baseline', whyWrong: 'An engineering metric. A CFO compares against the cost of the status quo instead.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'c.stakeholder.missing',
    mode: 'drill',
    nodeIds: ['cust.stakeholders'],
    difficulty: 'deep',
    explanation:
      'The person who can stop the project is frequently not in the kickoff. Security, legal, the works council, the platform team with a six-month queue, finding them in week one is cheap, and finding them in week ten is a schedule event.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Kickoff had the sponsor, the product owner and two engineers. Who do you go find in week one?',
      choices: [
        { id: 'a', text: 'Security, legal, and the owners of the systems you integrate with' },
        { id: 'b', text: 'Two more engineers, so the build starts at full capacity', whyWrong: 'Capacity is rarely the week-one constraint. Permission is.' },
        { id: 'c', text: 'The end users whose daily workflow the system will change', whyWrong: 'Valuable, and they cannot block you the way an unconsulted security lead can.' },
        { id: 'd', text: 'The sponsor’s manager, to confirm the funding is solid', whyWrong: 'Going over your sponsor’s head in week one costs the relationship you most need.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'c.discovery.silence',
    mode: 'drill',
    nodeIds: ['cust.discovery_q'],
    difficulty: 'deep',
    explanation:
      'Filling a pause with your own suggestion ends the disclosure. Most of the useful information in a discovery call arrives in the sentence after the one you were tempted to interrupt.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You ask an open question and the customer pauses for several seconds. What do you do?',
      choices: [
        { id: 'a', text: 'Offer an example of what other customers say here', whyWrong: 'Anchors their answer to your example and ends the disclosure you were about to get.' },
        { id: 'b', text: 'Rephrase the question in plainer, more concrete terms', whyWrong: 'Signals that the question was faulty when they were simply composing an answer.' },
        { id: 'c', text: 'Move on and circle back to it later in the call', whyWrong: 'Abandons the question that was working, and the return rarely feels natural.' },
        { id: 'd', text: 'Wait, since the useful answer usually follows' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 'c.ownership.language',
    mode: 'drill',
    nodeIds: ['cust.ownership'],
    difficulty: 'intro',
    explanation:
      'Interviewers listen for the difference between "I will" and "we are looking into it". The first is a commitment with a name and a date attached; the second is a status update disguised as an answer, and customers hear it as exactly that. The commitment is worth more when you also promise to report on the date either way, because then the customer does not have to chase you to find out whether it slipped.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'The customer asks when the connector issue will be resolved. Which answer lands best?',
      choices: [
        { id: 'a', text: '"We are looking into it and will keep you posted."', whyWrong: 'No owner, no date, no commitment. It is the phrase customers learn to distrust.' },
        { id: 'b', text: '"It sits with the platform team in their queue now."', whyWrong: 'Passes the parcel. The customer contracted with you, not with their backlog.' },
        { id: 'c', text: '"I will have a fix in staging by Thursday morning."' },
        { id: 'd', text: '"It should be resolved soon, likely within the week."', whyWrong: 'Hedged twice and unfalsifiable, and it will be quoted back at you on Friday.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 'c.pushback.acknowledge',
    mode: 'drill',
    nodeIds: ['cust.pushback', 'cust.saying_no'],
    difficulty: 'core',
    explanation:
      'Acknowledge the valid part first, and only then trade off. Leading with the objection makes the other person defend their position rather than engage with yours, you win the point and lose the decision.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'order',
      stem: 'A customer proposes something that would break their own data governance. Order your response.',
      steps: [
        'Acknowledge the underlying need and that it is real',
        'Name the specific constraint their proposal would breach',
        'Offer a concrete alternative that meets the need',
        'Ask what you have missed about their situation',
      ],
    },
  },
  {
    id: 'c.expectations.demo',
    mode: 'drill',
    nodeIds: ['cust.expectations', 'cust.explaining_ai'],
    difficulty: 'deep',
    explanation:
      'A demo sets an expectation whether or not you intend it to. Naming the gap between demo conditions and production conditions at the moment of the demo costs you nothing then, and saves you a difficult conversation later when the gap becomes visible. Say three things: that the examples are curated, what that means for the conclusions the room can safely draw, and the date you will show the same flow over their real data.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You are about to demo on curated examples because the real data is not connected yet. What do you say first?',
      choices: [
        { id: 'a', text: 'That these are curated examples, and when real data lands' },
        { id: 'b', text: 'Nothing up front, and mention it only if someone asks', whyWrong: 'Nobody asks, everyone assumes, and you spend the next month walking it back.' },
        { id: 'c', text: 'That the results so far should be treated as preliminary', whyWrong: 'Vague enough to be heard as modesty rather than as a material caveat.' },
        { id: 'd', text: 'That real data will look better once retrieval is tuned', whyWrong: 'A prediction you cannot support, offered at the moment expectations are set.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'c.badnews.options',
    mode: 'drill',
    nodeIds: ['cust.bad_news', 'del.discovery_scope'],
    difficulty: 'deep',
    explanation:
      'Bad news with a single outcome puts the customer in the position of accepting or objecting. Bad news with two costed options makes them a decision-maker, which changes the conversation from a complaint into a choice.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You must tell a customer about a three-week slip. What most improves how the conversation goes?',
      choices: [
        { id: 'a', text: 'A detailed root-cause account of what went wrong technically', whyWrong: 'Reads as justification. They will ask for the cause if they want it.' },
        { id: 'b', text: 'An apology and a commitment that the team will work weekends', whyWrong: 'Effort is not the constraint, and the promise is neither verifiable nor sustainable.' },
        { id: 'c', text: 'Two costed options: descope to hold the date, or move it' },
        { id: 'd', text: 'Waiting to raise it until you have a recovery plan in hand', whyWrong: 'Guarantees they hear it from someone else, which is the version that costs trust.' },
      ],
      correctId: 'c',
    },
  },
  {
    id: 'c.saying_no.champion',
    mode: 'drill',
    nodeIds: ['cust.saying_no', 'cust.stakeholders'],
    difficulty: 'edge',
    explanation:
      'When your champion asks for something out of bounds, the goal is to keep them a champion. Explaining the constraint plainly and handing them a narrower version they can announce lets them carry the governance conversation internally. Which is far more effective than you carrying it.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'Your strongest internal champion asks for a scope change that would trigger a compliance review nobody has started. What do you do?',
      choices: [
        { id: 'a', text: 'Agree now, and raise the compliance question afterwards', whyWrong: 'Their compliance function finds out after the announcement, and your champion wears it.' },
        { id: 'b', text: 'Name the constraint, offer a narrower version on their date' },
        { id: 'c', text: 'Decline, citing the policy on data classification', whyWrong: 'The right outcome delivered in the way most likely to cost you the champion.' },
        { id: 'd', text: 'Raise it directly with their compliance team yourself', whyWrong: 'Going around your champion on their own turf, which they will not forget.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'c.explaining.probability',
    mode: 'drill',
    nodeIds: ['cust.explaining_ai', 'ai.nondeterminism'],
    difficulty: 'deep',
    explanation:
      'A non-technical stakeholder needs a decision, not a mechanism. Reframing from "how accurate is it" to "what happens on the cases it gets wrong, and how would we know" gives them something they can act on, and introduces the review workflow the design needed anyway.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'What is the most useful reframe when a non-technical stakeholder asks how accurate the system is?',
      choices: [
        { id: 'a', text: '"Accuracy depends entirely on how you choose to measure it"', whyWrong: 'True, and heard as evasion by someone who has to make a decision today.' },
        { id: 'b', text: '"It performs about as well as a person doing the same task"', whyWrong: 'A claim you almost certainly cannot support, and it invites that exact comparison.' },
        { id: 'c', text: '"Let me walk you through the confusion matrix we produced"', whyWrong: 'The right artifact for a different audience, and it answers a question they did not ask.' },
        { id: 'd', text: '"Here is what happens when it is wrong, and how you find out"' },
      ],
      correctId: 'd',
    },
  },
  {
    id: 'c.meeting.notes',
    mode: 'drill',
    nodeIds: ['cust.expectations', 'del.discovery_scope'],
    difficulty: 'intro',
    explanation:
      'A short written summary after every consequential conversation costs five minutes and settles every later disagreement about what was agreed. It is the single cheapest habit in customer-facing engineering.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A verbal agreement was reached on a call about changing the delivery date. What do you do next?',
      choices: [
        { id: 'a', text: 'Send a short written summary of what was agreed, same day' },
        { id: 'b', text: 'Update the project plan and republish it to the team', whyWrong: 'Necessary, and a plan nobody on their side confirmed is not an agreement.' },
        { id: 'c', text: 'Brief your team so everyone works to the new date', whyWrong: 'Internal only. The recollection that gets disputed later is the customer’s.' },
        { id: 'd', text: 'Wait for the customer to confirm the change in writing', whyWrong: 'They will not, and an unconfirmed change quietly becomes one that never happened.' },
      ],
      correctId: 'a',
    },
  },
  {
    id: 'c.frustrated.first',
    mode: 'drill',
    nodeIds: ['cust.pushback', 'cust.bad_news'],
    difficulty: 'core',
    explanation:
      'A frustrated customer needs to be heard before they can hear you. Jumping to a solution while they are still describing the problem reads as not listening, and you will end up solving the wrong thing anyway.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'A customer opens a call visibly angry about a missed commitment. What do you do first?',
      choices: [
        { id: 'a', text: 'Apologize at once and move straight to the fix', whyWrong: 'Rushes past the part where they need to be certain you understood the damage.' },
        { id: 'b', text: 'Let them finish, then say back what went wrong' },
        { id: 'c', text: 'Explain the chain of events that caused the miss', whyWrong: 'Heard as excuse-making while they are still describing the consequences.' },
        { id: 'd', text: 'Offer a service credit against the next invoice', whyWrong: 'Buys off a relationship problem with money, and signals the fix is not coming.' },
      ],
      correctId: 'b',
    },
  },
  {
    id: 'c.discovery.constraint',
    mode: 'drill',
    nodeIds: ['cust.discovery_q', 'del.discovery_scope'],
    difficulty: 'edge',
    explanation:
      'The question with the highest information value is usually the one about a hard constraint nobody volunteered, residency, an unmovable date, a system that cannot be touched. Those reshape the architecture, and they rarely appear in the brief.',
    citations: cite('waf'),
    origin: 'seed',
    criticScore: null,
    payload: {
      kind: 'mcq',
      stem: 'You have time for one more question in a first discovery call. Which has the highest expected value?',
      choices: [
        { id: 'a', text: '"What constraint have we not talked about that would change how we build this?"' },
        { id: 'b', text: '"What is your timeline?"', whyWrong: 'You will get a date. Dates rarely change the architecture; constraints do.' },
        { id: 'c', text: '"Who else should be involved?"', whyWrong: 'Genuinely valuable, and second to surfacing an unstated hard constraint.' },
        { id: 'd', text: '"What does success look like?"', whyWrong: 'Essential and you should already have asked it earlier in the call.' },
      ],
      correctId: 'a',
    },
  },
];
